# PDF path
pdf_path: data/charles_darwin_origin_of_species.pdf
# Embedding model 
embedding_model:
  name: mxbai-embed-large
  version: latest

# Persist directory
persist_directory : vector_stores/
texts_filename: texts/

batch_size: 16
# Chunk parameters
chunk:
  size: 3000
  overlap: 100

# Chat model
chat_model: mistral
